language: node_js
node_js:
  - '7'
services:
  - mysql
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
env:
  - CXX=g++-4.8 APP_SECRET='dumbSecret' DB_ENDPOINT='end.point/fake' DB_PORT=3307 AWS_BUCKET='assassinTag' AWS_ACCESS_KEY_ID='fakekey' AWS_SECRET_ACCESS_KEY='fakekey' API_URL='http://localhost:7000' PORT=7000 DB_USER='somefakeuser' DB_NAME='somename' DB_PASS='coolpassword'

sudo: required
before_script: npm i
script:
  - npm start
